# Generated by Django 3.2.8 on 2021-10-20 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20211020_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
