# Generated by Django 4.0 on 2021-12-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='u_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='user name'),
        ),
    ]
