# Generated by Django 4.0 on 2021-12-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pass', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
