# Generated by Django 4.0 on 2021-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='u_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='user name'),
        ),
    ]
